name: "\U0001F4A1 Feature Request"
description: Let us know what extra functionality you need
title: "[FEAT]: <catchy title>"
labels: ["feature"]
assignees:
  - maximyudayev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an improvement, an extension, or a new feature to our system. Let us hear it!
  - type: checkboxes
    attributes:
      label: Is this feature in the roadmap already?
      description: Please check if the similar feature has already been proposed in another feature request, or is already mentioned in the next release plans.
      options:
      - label: I have checked for duplicates of my proposal
        required: true
  - type: textarea
    id: summary
    attributes:
      label: Feature description
      description: What extra functionality would you like to see added into our system?
      placeholder: e.g. A PyTorch worker Node that consumes data of different Producer Nodes and does inference in realtime.  
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Feature type
      description: Which category best describes your proposal?
      multiple: false
      options:
        - New unsupported sensor/device
        - Usability improvement
        - Automation
        - System reliability
        - Developer-oriented
        - Performance
      default: 0
  - type: dropdown
    id: is_bottleneck
    attributes:
      label: Is it a bottleneck?
      description: Does it prevent you from using our system in the desired way to reach your goals?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
